// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BE1.Models;

public partial class BankCard
{
    public int BankCardId { get; set; }

    public string AccountName { get; set; }

    public string CardNumber { get; set; }

    public DateOnly ExpirationDate { get; set; }

    public string CardType { get; set; }

    public virtual Account AccountNameNavigation { get; set; }
}