// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BE1.Models;

public partial class FavoriteHotel
{
    public int FavoriteHotelId { get; set; }

    public string AccountName { get; set; }

    public int HotelId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Account AccountNameNavigation { get; set; }

    public virtual Hotel Hotel { get; set; }
}