// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BE1.Models;

public partial class Hotel
{
    public int HotelId { get; set; }

    public string HotelName { get; set; }

    public string Address { get; set; }

    public string City { get; set; }

    public string District { get; set; }

    public string State { get; set; }

    public string Description { get; set; }

    public virtual ICollection<FavoriteHotel> FavoriteHotels { get; set; } = new List<FavoriteHotel>();

    public virtual ICollection<HotelBooking> HotelBookings { get; set; } = new List<HotelBooking>();

    public virtual ICollection<HotelImage> HotelImages { get; set; } = new List<HotelImage>();

    public virtual ICollection<HotelReview> HotelReviews { get; set; } = new List<HotelReview>();

    public virtual ICollection<RoomType> RoomTypes { get; set; } = new List<RoomType>();

    public virtual ICollection<Service> Services { get; set; } = new List<Service>();

    public virtual ICollection<Social> Socials { get; set; } = new List<Social>();
}