// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace BE1.Models;

public partial class HotelContext : DbContext
{
    public HotelContext(DbContextOptions<HotelContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Account> Accounts { get; set; }

    public virtual DbSet<BankCard> BankCards { get; set; }

    public virtual DbSet<FavoriteHotel> FavoriteHotels { get; set; }

    public virtual DbSet<Hotel> Hotels { get; set; }

    public virtual DbSet<HotelBooking> HotelBookings { get; set; }

    public virtual DbSet<HotelImage> HotelImages { get; set; }

    public virtual DbSet<HotelInvoice> HotelInvoices { get; set; }

    public virtual DbSet<HotelReview> HotelReviews { get; set; }

    public virtual DbSet<HotelReviewImage> HotelReviewImages { get; set; }

    public virtual DbSet<InvoiceDetail> InvoiceDetails { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<RefreshToken> RefreshTokens { get; set; }

    public virtual DbSet<Room> Rooms { get; set; }

    public virtual DbSet<RoomImage> RoomImages { get; set; }

    public virtual DbSet<RoomReview> RoomReviews { get; set; }

    public virtual DbSet<RoomReviewImage> RoomReviewImages { get; set; }

    public virtual DbSet<RoomType> RoomTypes { get; set; }

    public virtual DbSet<Service> Services { get; set; }

    public virtual DbSet<ServiceBooking> ServiceBookings { get; set; }

    public virtual DbSet<ServiceImage> ServiceImages { get; set; }

    public virtual DbSet<ServiceInvoice> ServiceInvoices { get; set; }

    public virtual DbSet<ServiceReview> ServiceReviews { get; set; }

    public virtual DbSet<ServicesReviewImage> ServicesReviewImages { get; set; }

    public virtual DbSet<Social> Socials { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Account>(entity =>
        {
            entity.HasKey(e => e.AccountName).HasName("PK__Accounts__6894C54BA497ACC0");

            entity.HasIndex(e => e.Email, "UQ__Accounts__AB6E6164715960D7").IsUnique();

            entity.Property(e => e.AccountName)
                .HasMaxLength(255)
                .HasColumnName("account_name");
            entity.Property(e => e.AvatarUrl)
                .HasMaxLength(255)
                .HasColumnName("Avatar_URL");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("email");
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("first_name");
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("last_name");
            entity.Property(e => e.Nationality).HasMaxLength(100);
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("password_hash");
            entity.Property(e => e.Phone)
                .HasMaxLength(20)
                .HasColumnName("phone");
            entity.Property(e => e.Role)
                .HasMaxLength(50)
                .HasColumnName("role");
            entity.Property(e => e.UpdateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("update_at");
        });

        modelBuilder.Entity<BankCard>(entity =>
        {
            entity.HasKey(e => e.BankCardId).HasName("PK__Bank_Car__5D513DB1C52AA0E2");

            entity.ToTable("Bank_Card");

            entity.HasIndex(e => e.CardNumber, "UQ__Bank_Car__1E6E0AF48AD72547").IsUnique();

            entity.Property(e => e.BankCardId).HasColumnName("bank_card_id");
            entity.Property(e => e.AccountName)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("account_name");
            entity.Property(e => e.CardNumber)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("card_number");
            entity.Property(e => e.CardType)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("card_type");
            entity.Property(e => e.ExpirationDate).HasColumnName("expiration_date");

            entity.HasOne(d => d.AccountNameNavigation).WithMany(p => p.BankCards)
                .HasForeignKey(d => d.AccountName)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BankCard_Accounts");
        });

        modelBuilder.Entity<FavoriteHotel>(entity =>
        {
            entity.HasKey(e => e.FavoriteHotelId).HasName("PK__Favorite__575B0BE6E9DA9647");

            entity.ToTable("Favorite_Hotels");

            entity.Property(e => e.FavoriteHotelId).HasColumnName("favorite_hotel_id");
            entity.Property(e => e.AccountName)
                .HasMaxLength(255)
                .HasColumnName("account_name");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.HotelId).HasColumnName("hotel_id");

            entity.HasOne(d => d.AccountNameNavigation).WithMany(p => p.FavoriteHotels)
                .HasForeignKey(d => d.AccountName)
                .HasConstraintName("FK__Favorite___accou__70DDC3D8");

            entity.HasOne(d => d.Hotel).WithMany(p => p.FavoriteHotels)
                .HasForeignKey(d => d.HotelId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Favorite___hotel__71D1E811");
        });

        modelBuilder.Entity<Hotel>(entity =>
        {
            entity.HasKey(e => e.HotelId).HasName("PK__Hotels__45FE7E264FA7F8A7");

            entity.Property(e => e.HotelId).HasColumnName("hotel_id");
            entity.Property(e => e.Address)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("address");
            entity.Property(e => e.City)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("city");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.District)
                .HasMaxLength(100)
                .HasColumnName("district");
            entity.Property(e => e.HotelName)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("hotel_name");
            entity.Property(e => e.State)
                .HasMaxLength(100)
                .HasColumnName("state");
        });

        modelBuilder.Entity<HotelBooking>(entity =>
        {
            entity.HasKey(e => e.HotelBookingId).HasName("PK__Hotel_Bo__4D87FD92777E4E8C");

            entity.ToTable("Hotel_Bookings");

            entity.Property(e => e.HotelBookingId).HasColumnName("hotel_booking_id");
            entity.Property(e => e.AccountName)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("account_name");
            entity.Property(e => e.CheckInDate).HasColumnName("check_in_date");
            entity.Property(e => e.CheckOutDate).HasColumnName("check_out_date");
            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("create_at");
            entity.Property(e => e.HotelId).HasColumnName("hotel_id");
            entity.Property(e => e.RoomId).HasColumnName("room_id");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.TotalPrice)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("total_price");

            entity.HasOne(d => d.AccountNameNavigation).WithMany(p => p.HotelBookings)
                .HasForeignKey(d => d.AccountName)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_HotelBookings_Accounts");

            entity.HasOne(d => d.Hotel).WithMany(p => p.HotelBookings)
                .HasForeignKey(d => d.HotelId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_HotelBookings_Hotels");

            entity.HasOne(d => d.Room).WithMany(p => p.HotelBookings)
                .HasForeignKey(d => d.RoomId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_HotelBookings_Rooms");
        });

        modelBuilder.Entity<HotelImage>(entity =>
        {
            entity.HasKey(e => e.HotelImagesId).HasName("PK__Hotel_Im__039E3CC90FD8C0AE");

            entity.ToTable("Hotel_Images");

            entity.Property(e => e.HotelImagesId).HasColumnName("Hotel_Images_id");
            entity.Property(e => e.HotelId).HasColumnName("hotel_id");
            entity.Property(e => e.ImageUrl)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("image_url");

            entity.HasOne(d => d.Hotel).WithMany(p => p.HotelImages)
                .HasForeignKey(d => d.HotelId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_HotelImages_Hotels");
        });

        modelBuilder.Entity<HotelInvoice>(entity =>
        {
            entity.HasKey(e => e.HotelInvoiceId).HasName("PK__Hotel_In__53B4F48CBAD884CC");

            entity.ToTable("Hotel_Invoices");

            entity.Property(e => e.HotelInvoiceId).HasColumnName("hotel_invoice_id");
            entity.Property(e => e.HotelBookingId).HasColumnName("hotel_booking_id");
            entity.Property(e => e.InvoiceDate).HasColumnName("invoice_date");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.TotalAmount)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("total_amount");

            entity.HasOne(d => d.HotelBooking).WithMany(p => p.HotelInvoices)
                .HasForeignKey(d => d.HotelBookingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_HotelInvoices_HotelBookings");
        });

        modelBuilder.Entity<HotelReview>(entity =>
        {
            entity.HasKey(e => e.HotelReviewId).HasName("PK__Hotel_Re__1E97B0F45DE4288D");

            entity.ToTable("Hotel_Reviews");

            entity.Property(e => e.HotelReviewId).HasColumnName("hotel_review_id");
            entity.Property(e => e.AccountName)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("account_name");
            entity.Property(e => e.HotelId).HasColumnName("hotel_id");
            entity.Property(e => e.Rating).HasColumnName("rating");
            entity.Property(e => e.ReviewDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnName("review_date");
            entity.Property(e => e.ReviewText).HasColumnName("review_text");

            entity.HasOne(d => d.AccountNameNavigation).WithMany(p => p.HotelReviews)
                .HasForeignKey(d => d.AccountName)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_HotelReviews_Accounts");

            entity.HasOne(d => d.Hotel).WithMany(p => p.HotelReviews)
                .HasForeignKey(d => d.HotelId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_HotelReviews_Hotels");
        });

        modelBuilder.Entity<HotelReviewImage>(entity =>
        {
            entity.HasKey(e => e.HotelReviewImageId).HasName("PK__Hotel_Re__64875281ABF71757");

            entity.ToTable("Hotel_Review_Images");

            entity.Property(e => e.HotelReviewImageId).HasColumnName("hotel_review_image_id");
            entity.Property(e => e.HotelReviewId).HasColumnName("hotel_review_id");
            entity.Property(e => e.ImageUrl)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("image_url");

            entity.HasOne(d => d.HotelReview).WithMany(p => p.HotelReviewImages)
                .HasForeignKey(d => d.HotelReviewId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_HotelReviewImages_HotelReviews");
        });

        modelBuilder.Entity<InvoiceDetail>(entity =>
        {
            entity.HasKey(e => e.InvoiceDetailId).HasName("PK__Invoice___84908DB6B0554BAC");

            entity.ToTable("Invoice_Details");

            entity.Property(e => e.InvoiceDetailId).HasColumnName("invoice_detail_id");
            entity.Property(e => e.InvoiceId).HasColumnName("invoice_id");
            entity.Property(e => e.InvoiceType)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("invoice_type");
            entity.Property(e => e.Price)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("price");
            entity.Property(e => e.Quantity).HasColumnName("quantity");
            entity.Property(e => e.RoomId).HasColumnName("room_id");
            entity.Property(e => e.ServiceId).HasColumnName("service_id");

            entity.HasOne(d => d.Invoice).WithMany(p => p.InvoiceDetails)
                .HasForeignKey(d => d.InvoiceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_InvoiceDetails_HotelInvoices");

            entity.HasOne(d => d.Room).WithMany(p => p.InvoiceDetails)
                .HasForeignKey(d => d.RoomId)
                .HasConstraintName("FK_InvoiceDetails_Rooms");

            entity.HasOne(d => d.Service).WithMany(p => p.InvoiceDetails)
                .HasForeignKey(d => d.ServiceId)
                .HasConstraintName("FK_InvoiceDetails_Services");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.PaymentId).HasName("PK__Payments__ED1FC9EA20396D9C");

            entity.Property(e => e.PaymentId).HasColumnName("payment_id");
            entity.Property(e => e.Amount)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("amount");
            entity.Property(e => e.HotelBookingId).HasColumnName("hotel_booking_id");
            entity.Property(e => e.PaymentDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("payment_date");
            entity.Property(e => e.RestaurantBookingId).HasColumnName("restaurant_booking_id");
            entity.Property(e => e.ServiceBookingId).HasColumnName("service_booking_id");

            entity.HasOne(d => d.HotelBooking).WithMany(p => p.Payments)
                .HasForeignKey(d => d.HotelBookingId)
                .HasConstraintName("FK_Payments_HotelBookings");

            entity.HasOne(d => d.ServiceBooking).WithMany(p => p.Payments)
                .HasForeignKey(d => d.ServiceBookingId)
                .HasConstraintName("FK_Payments_ServiceBookings");
        });

        modelBuilder.Entity<RefreshToken>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__RefreshT__3214EC07487482D4");

            entity.Property(e => e.AccountName)
                .HasMaxLength(255)
                .HasColumnName("account_name");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Revoked).HasDefaultValue(false);
            entity.Property(e => e.Token).HasMaxLength(500);

            entity.HasOne(d => d.AccountNameNavigation).WithMany(p => p.RefreshTokens)
                .HasForeignKey(d => d.AccountName)
                .HasConstraintName("FK__RefreshTo__accou__3E52440B");
        });

        modelBuilder.Entity<Room>(entity =>
        {
            entity.HasKey(e => e.RoomId).HasName("PK__Rooms__19675A8AC396BAB9");

            entity.Property(e => e.RoomId).HasColumnName("room_id");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.MaxOccupancy).HasColumnName("max_occupancy");
            entity.Property(e => e.PricePerNight)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("price_per_night");
            entity.Property(e => e.RoomCount).HasColumnName("room_count");
            entity.Property(e => e.RoomTypeId).HasColumnName("room_type_id");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("status");

            entity.HasOne(d => d.RoomType).WithMany(p => p.Rooms)
                .HasForeignKey(d => d.RoomTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Rooms_RoomTypes");
        });

        modelBuilder.Entity<RoomImage>(entity =>
        {
            entity.HasKey(e => e.ImageId).HasName("PK__Room_Ima__DC9AC9554275F223");

            entity.ToTable("Room_Images");

            entity.Property(e => e.ImageId).HasColumnName("image_id");
            entity.Property(e => e.ImageUrl)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("image_url");
            entity.Property(e => e.RoomId).HasColumnName("room_id");

            entity.HasOne(d => d.Room).WithMany(p => p.RoomImages)
                .HasForeignKey(d => d.RoomId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RoomImages_Rooms");
        });

        modelBuilder.Entity<RoomReview>(entity =>
        {
            entity.HasKey(e => e.RoomReviewId).HasName("PK__Room_Rev__C28CA8A345677882");

            entity.ToTable("Room_Reviews");

            entity.Property(e => e.RoomReviewId).HasColumnName("room_review_id");
            entity.Property(e => e.AccountName)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("account_name");
            entity.Property(e => e.Rating).HasColumnName("rating");
            entity.Property(e => e.ReviewDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnName("review_date");
            entity.Property(e => e.ReviewText).HasColumnName("review_text");
            entity.Property(e => e.RoomId).HasColumnName("room_id");

            entity.HasOne(d => d.AccountNameNavigation).WithMany(p => p.RoomReviews)
                .HasForeignKey(d => d.AccountName)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RoomReviews_Accounts");

            entity.HasOne(d => d.Room).WithMany(p => p.RoomReviews)
                .HasForeignKey(d => d.RoomId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RoomReviews_Rooms");
        });

        modelBuilder.Entity<RoomReviewImage>(entity =>
        {
            entity.HasKey(e => e.RoomReviewImageId).HasName("PK__Room_Rev__F82C734F49FEE7B9");

            entity.ToTable("Room_Review_Images");

            entity.Property(e => e.RoomReviewImageId).HasColumnName("room_review_image_id");
            entity.Property(e => e.ImageUrl)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("image_url");
            entity.Property(e => e.RoomReviewId).HasColumnName("room_review_id");

            entity.HasOne(d => d.RoomReview).WithMany(p => p.RoomReviewImages)
                .HasForeignKey(d => d.RoomReviewId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RoomReviewImages_RoomReviews");
        });

        modelBuilder.Entity<RoomType>(entity =>
        {
            entity.HasKey(e => e.RoomTypeId).HasName("PK__Room_Typ__42395E84CCBBD7E1");

            entity.ToTable("Room_Types");

            entity.Property(e => e.RoomTypeId).HasColumnName("room_type_id");
            entity.Property(e => e.HotelId).HasColumnName("hotel_id");
            entity.Property(e => e.TypeName)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("type_name");

            entity.HasOne(d => d.Hotel).WithMany(p => p.RoomTypes)
                .HasForeignKey(d => d.HotelId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RoomTypes_Hotels");
        });

        modelBuilder.Entity<Service>(entity =>
        {
            entity.HasKey(e => e.ServiceId).HasName("PK__Services__3E0DB8AF5A403BF9");

            entity.Property(e => e.ServiceId).HasColumnName("service_id");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.HotelId).HasColumnName("hotel_id");
            entity.Property(e => e.ServiceName)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("service_name");
            entity.Property(e => e.ServicePrice)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("service_price");
            entity.Property(e => e.ServiceType)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("service_type");

            entity.HasOne(d => d.Hotel).WithMany(p => p.Services)
                .HasForeignKey(d => d.HotelId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Services_Hotels");
        });

        modelBuilder.Entity<ServiceBooking>(entity =>
        {
            entity.HasKey(e => e.ServiceBookingId).HasName("PK__Service___E15424362056FDAC");

            entity.ToTable("Service_Bookings");

            entity.Property(e => e.ServiceBookingId).HasColumnName("service_booking_id");
            entity.Property(e => e.HotelBookingId).HasColumnName("hotel_booking_id");
            entity.Property(e => e.Quantity).HasColumnName("quantity");
            entity.Property(e => e.ServiceId).HasColumnName("service_id");
            entity.Property(e => e.TotalPrice)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("total_price");

            entity.HasOne(d => d.HotelBooking).WithMany(p => p.ServiceBookings)
                .HasForeignKey(d => d.HotelBookingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ServiceBookings_HotelBookings");

            entity.HasOne(d => d.Service).WithMany(p => p.ServiceBookings)
                .HasForeignKey(d => d.ServiceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ServiceBookings_Services");
        });

        modelBuilder.Entity<ServiceImage>(entity =>
        {
            entity.HasKey(e => e.ImageId).HasName("PK__Service___DC9AC955A49E4BEE");

            entity.ToTable("Service_Images");

            entity.Property(e => e.ImageId).HasColumnName("image_id");
            entity.Property(e => e.ImageUrl)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("image_url");
            entity.Property(e => e.ServiceId).HasColumnName("service_id");

            entity.HasOne(d => d.Service).WithMany(p => p.ServiceImages)
                .HasForeignKey(d => d.ServiceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ServiceImages_Services");
        });

        modelBuilder.Entity<ServiceInvoice>(entity =>
        {
            entity.HasKey(e => e.ServiceInvoiceId).HasName("PK__Service___A5F8C773F0A4DE70");

            entity.ToTable("Service_Invoices");

            entity.Property(e => e.ServiceInvoiceId).HasColumnName("service_invoice_id");
            entity.Property(e => e.InvoiceDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("invoice_date");
            entity.Property(e => e.ServiceBookingId).HasColumnName("service_booking_id");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.TotalAmount)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("total_amount");

            entity.HasOne(d => d.ServiceBooking).WithMany(p => p.ServiceInvoices)
                .HasForeignKey(d => d.ServiceBookingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ServiceInvoices_ServiceBookings");
        });

        modelBuilder.Entity<ServiceReview>(entity =>
        {
            entity.HasKey(e => e.ServiceReviewId).HasName("PK__Service___4FF2E5DDCE0D32D1");

            entity.ToTable("Service_Reviews");

            entity.Property(e => e.ServiceReviewId).HasColumnName("service_review_id");
            entity.Property(e => e.AccountName)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("account_name");
            entity.Property(e => e.Rating).HasColumnName("rating");
            entity.Property(e => e.ReviewDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnName("review_date");
            entity.Property(e => e.ReviewText).HasColumnName("review_text");
            entity.Property(e => e.ServiceId).HasColumnName("service_id");

            entity.HasOne(d => d.AccountNameNavigation).WithMany(p => p.ServiceReviews)
                .HasForeignKey(d => d.AccountName)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ServiceReviews_Accounts");

            entity.HasOne(d => d.Service).WithMany(p => p.ServiceReviews)
                .HasForeignKey(d => d.ServiceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ServiceReviews_Services");
        });

        modelBuilder.Entity<ServicesReviewImage>(entity =>
        {
            entity.HasKey(e => e.ServicesReviewImageId).HasName("PK__Services__3BEEEB89E92504BA");

            entity.ToTable("Services_Review_Images");

            entity.Property(e => e.ServicesReviewImageId).HasColumnName("services_review_image_id");
            entity.Property(e => e.ImageUrl)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("image_url");
            entity.Property(e => e.ServiceReviewId).HasColumnName("service_review_id");

            entity.HasOne(d => d.ServiceReview).WithMany(p => p.ServicesReviewImages)
                .HasForeignKey(d => d.ServiceReviewId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ServicesReviewImages_ServiceReviews");
        });

        modelBuilder.Entity<Social>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Social__3214EC272F7A2C43");

            entity.ToTable("Social");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.HotelId).HasColumnName("hotel_id");
            entity.Property(e => e.LinkUrl)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("Link_URL");

            entity.HasOne(d => d.Hotel).WithMany(p => p.Socials)
                .HasForeignKey(d => d.HotelId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Social_Hotels");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}