// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BE1.Models;

public partial class HotelReviewImage
{
    public int HotelReviewImageId { get; set; }

    public int HotelReviewId { get; set; }

    public string ImageUrl { get; set; }

    public virtual HotelReview HotelReview { get; set; }
}