// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BE1.Models;

public partial class HotelInvoice
{
    public int HotelInvoiceId { get; set; }

    public int HotelBookingId { get; set; }

    public DateOnly InvoiceDate { get; set; }

    public decimal TotalAmount { get; set; }

    public string Status { get; set; }

    public virtual HotelBooking HotelBooking { get; set; }

    public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; } = new List<InvoiceDetail>();
}