// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BE1.Models;

public partial class Payment
{
    public int PaymentId { get; set; }

    public int? HotelBookingId { get; set; }

    public int? ServiceBookingId { get; set; }

    public int? RestaurantBookingId { get; set; }

    public decimal Amount { get; set; }

    public DateTime? PaymentDate { get; set; }

    public virtual HotelBooking HotelBooking { get; set; }

    public virtual ServiceBooking ServiceBooking { get; set; }
}