// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BE1.newModels;

public partial class HotelImage
{
    public int HotelImagesId { get; set; }

    public int HotelId { get; set; }

    public string ImageUrl { get; set; }

    public virtual Hotel Hotel { get; set; }
}