// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BE1.newModels;

public partial class InvoiceDetail
{
    public int InvoiceDetailId { get; set; }

    public int InvoiceId { get; set; }

    public string InvoiceType { get; set; }

    public int? RoomId { get; set; }

    public int? ServiceId { get; set; }

    public int Quantity { get; set; }

    public decimal Price { get; set; }

    public virtual HotelInvoice Invoice { get; set; }

    public virtual Room Room { get; set; }

    public virtual Service Service { get; set; }
}