// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BE1.newModels;

public partial class RefreshToken
{
    public int Id { get; set; }

    public string AccountName { get; set; }

    public string Token { get; set; }

    public DateTime? ExpiryDate { get; set; }

    public bool? Revoked { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Account AccountNameNavigation { get; set; }
}