// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BE1.newModels;

public partial class Room
{
    public int RoomId { get; set; }

    public int RoomTypeId { get; set; }

    public decimal PricePerNight { get; set; }

    public string Status { get; set; }

    public string Description { get; set; }

    public int MaxOccupancy { get; set; }

    public int RoomCount { get; set; }

    public virtual ICollection<HotelBooking> HotelBookings { get; set; } = new List<HotelBooking>();

    public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; } = new List<InvoiceDetail>();

    public virtual ICollection<RoomImage> RoomImages { get; set; } = new List<RoomImage>();

    public virtual ICollection<RoomReview> RoomReviews { get; set; } = new List<RoomReview>();

    public virtual RoomType RoomType { get; set; }
}