// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BE1.newModels;

public partial class RoomType
{
    public int RoomTypeId { get; set; }

    public int HotelId { get; set; }

    public string TypeName { get; set; }

    public virtual Hotel Hotel { get; set; }

    public virtual ICollection<Room> Rooms { get; set; } = new List<Room>();
}