// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hotel_1.Models
{
    public partial class Account
    {
        public Account()
        {
            BankCards = new HashSet<BankCard>();
            BillsHotels = new HashSet<BillsHotel>();
            BookingHistories = new HashSet<BookingHistory>();
            HotelBookings = new HashSet<HotelBooking>();
            HotelReviews = new HashSet<HotelReview>();
            Notifications = new HashSet<Notification>();
            Reservations = new HashSet<Reservation>();
            RoomReviews = new HashSet<RoomReview>();
            ServiceReviews = new HashSet<ServiceReview>();
        }

        public string AccountName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PasswordHash { get; set; }
        public string Phone { get; set; }
        public string Role { get; set; }
        public string AvatarUrl { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdateAt { get; set; }

        public virtual ICollection<BankCard> BankCards { get; set; }
        public virtual ICollection<BillsHotel> BillsHotels { get; set; }
        public virtual ICollection<BookingHistory> BookingHistories { get; set; }
        public virtual ICollection<HotelBooking> HotelBookings { get; set; }
        public virtual ICollection<HotelReview> HotelReviews { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<Reservation> Reservations { get; set; }
        public virtual ICollection<RoomReview> RoomReviews { get; set; }
        public virtual ICollection<ServiceReview> ServiceReviews { get; set; }
    }
}