// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hotel_1.Models
{
    public partial class BankCard
    {
        public int CardId { get; set; }
        public string AccountName { get; set; }
        public string CardName { get; set; }
        public string CardNumber { get; set; }
        public string CardCvv { get; set; }
        public DateTime ExpirationDate { get; set; }
        public DateTime? CreateAt { get; set; }

        public virtual Account AccountNameNavigation { get; set; }
    }
}