// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hotel_1.Models
{
    public partial class BillsHotelDetail
    {
        public int BillHotelDetailId { get; set; }
        public int BillHotelId { get; set; }
        public int RoomId { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
        public int Quantity { get; set; }

        public virtual BillsHotel BillHotel { get; set; }
        public virtual Room Room { get; set; }
    }
}