// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hotel_1.Models
{
    public partial class BillsHotel
    {
        public BillsHotel()
        {
            BillsHotelDetails = new HashSet<BillsHotelDetail>();
            BillsServices = new HashSet<BillsService>();
        }

        public int BillHotelId { get; set; }
        public string AccountName { get; set; }
        public int HotelBookingId { get; set; }
        public DateTime? OrderDate { get; set; }
        public decimal TotalAmount { get; set; }
        public string Status { get; set; }

        public virtual Account AccountNameNavigation { get; set; }
        public virtual HotelBooking HotelBooking { get; set; }
        public virtual ICollection<BillsHotelDetail> BillsHotelDetails { get; set; }
        public virtual ICollection<BillsService> BillsServices { get; set; }
    }
}