// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hotel_1.Models
{
    public partial class BillsService
    {
        public BillsService()
        {
            BillsServiceDetails = new HashSet<BillsServiceDetail>();
        }

        public int BillServiceId { get; set; }
        public int BillHotelId { get; set; }
        public int ServiceBookingId { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }

        public virtual BillsHotel BillHotel { get; set; }
        public virtual ServiceBooking ServiceBooking { get; set; }
        public virtual ICollection<BillsServiceDetail> BillsServiceDetails { get; set; }
    }
}