// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hotel_1.Models
{
    public partial class BillsServiceDetail
    {
        public int BillServiceDetailId { get; set; }
        public int BillServiceId { get; set; }
        public int ServiceId { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
        public int Quantity { get; set; }

        public virtual BillsService BillService { get; set; }
        public virtual Service Service { get; set; }
    }
}