// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hotel_1.Models
{
    public partial class BookingHistory
    {
        public int BookingHistoryId { get; set; }
        public string AccountName { get; set; }
        public int HotelBookingId { get; set; }
        public DateTime? BookingDate { get; set; }

        public virtual Account AccountNameNavigation { get; set; }
        public virtual HotelBooking HotelBooking { get; set; }
    }
}