// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hotel_1.Models
{
    public partial class HotelBooking
    {
        public HotelBooking()
        {
            BillsHotels = new HashSet<BillsHotel>();
            BookingHistories = new HashSet<BookingHistory>();
            Payments = new HashSet<Payment>();
            ServiceBookings = new HashSet<ServiceBooking>();
        }

        public int HotelBookingId { get; set; }
        public string AccountName { get; set; }
        public int RoomId { get; set; }
        public int HotelId { get; set; }
        public DateTime CheckInDate { get; set; }
        public DateTime CheckOutDate { get; set; }
        public decimal? TotalPrice { get; set; }
        public string Status { get; set; }
        public DateTime? CreateAt { get; set; }

        public virtual Account AccountNameNavigation { get; set; }
        public virtual Hotel Hotel { get; set; }
        public virtual Room Room { get; set; }
        public virtual ICollection<BillsHotel> BillsHotels { get; set; }
        public virtual ICollection<BookingHistory> BookingHistories { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<ServiceBooking> ServiceBookings { get; set; }
    }
}