// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hotel_1.Models
{
    public partial class Hotel
    {
        public Hotel()
        {
            HotelBookings = new HashSet<HotelBooking>();
            HotelImages = new HashSet<HotelImage>();
            HotelReviews = new HashSet<HotelReview>();
            RoomTypes = new HashSet<RoomType>();
            Socials = new HashSet<Social>();
        }

        public int HotelId { get; set; }
        public string HotelName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string State { get; set; }
        public string Description { get; set; }

        public virtual ICollection<HotelBooking> HotelBookings { get; set; }
        public virtual ICollection<HotelImage> HotelImages { get; set; }
        public virtual ICollection<HotelReview> HotelReviews { get; set; }
        public virtual ICollection<RoomType> RoomTypes { get; set; }
        public virtual ICollection<Social> Socials { get; set; }
    }
}