// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hotel_1.Models
{
    public partial class HotelReview
    {
        public int HotelReviewId { get; set; }
        public string AccountName { get; set; }
        public int HotelId { get; set; }
        public int? Rating { get; set; }
        public string ReviewText { get; set; }
        public DateTime? ReviewDate { get; set; }

        public virtual Account AccountNameNavigation { get; set; }
        public virtual Hotel Hotel { get; set; }
    }
}