// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hotel_1.Models
{
    public partial class Payment
    {
        public int PaymentId { get; set; }
        public int? HotelBookingId { get; set; }
        public int? ServiceBookingId { get; set; }
        public string PaymentMethod { get; set; }
        public decimal? PaymentAmount { get; set; }
        public DateTime? PaymentDate { get; set; }

        public virtual HotelBooking HotelBooking { get; set; }
        public virtual ServiceBooking ServiceBooking { get; set; }
    }
}