// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hotel_1.Models
{
    public partial class Reservation
    {
        public int ReservationId { get; set; }
        public string AccountName { get; set; }
        public DateTime ReservationDate { get; set; }
        public string ReservationType { get; set; }
        public string Status { get; set; }

        public virtual Account AccountNameNavigation { get; set; }
    }
}