// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hotel_1.Models
{
    public partial class RoomReview
    {
        public RoomReview()
        {
            RoomReviewImages = new HashSet<RoomReviewImage>();
        }

        public int RoomReviewId { get; set; }
        public string AccountName { get; set; }
        public int RoomId { get; set; }
        public int? Rating { get; set; }
        public string ReviewText { get; set; }
        public DateTime ReviewDate { get; set; }

        public virtual Account AccountNameNavigation { get; set; }
        public virtual Room Room { get; set; }
        public virtual ICollection<RoomReviewImage> RoomReviewImages { get; set; }
    }
}