// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hotel_1.Models
{
    public partial class ServiceImage
    {
        public int ImageId { get; set; }
        public int? ServiceId { get; set; }
        public string ImageUrl { get; set; }

        public virtual Service Service { get; set; }
    }
}