// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hotel_1.Models
{
    public partial class ServiceReview
    {
        public ServiceReview()
        {
            ServicesReviewImages = new HashSet<ServicesReviewImage>();
        }

        public int ServiceReviewId { get; set; }
        public string AccountName { get; set; }
        public int ServiceId { get; set; }
        public int? Rating { get; set; }
        public string ReviewText { get; set; }
        public DateTime ReviewDate { get; set; }

        public virtual Account AccountNameNavigation { get; set; }
        public virtual Service Service { get; set; }
        public virtual ICollection<ServicesReviewImage> ServicesReviewImages { get; set; }
    }
}