// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hotel_1.Models
{
    public partial class ServiceBooking
    {
        public ServiceBooking()
        {
            BillsServices = new HashSet<BillsService>();
            Payments = new HashSet<Payment>();
        }

        public int ServiceBookingId { get; set; }
        public int HotelBookingId { get; set; }
        public int ServiceId { get; set; }
        public int Quantity { get; set; }
        public decimal? TotalPrice { get; set; }

        public virtual HotelBooking HotelBooking { get; set; }
        public virtual Service Service { get; set; }
        public virtual ICollection<BillsService> BillsServices { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
    }
}